### ISSUE TITLE
*AttributeError: 'DataFrame' object has no attribute 'append'*

### ISSUE THREAD

**Issue by Benjamin-Loison** [Benjamin-Loison/UMAP23_KARSCombiningGNNsEncSentenceEnc#6]
```
Traceback (most recent call last):
  File "deep_arch.py", line 278, in <module>
    top_5_scores = top_scores(predictions,5)
  File "deep_arch.py", line 104, in top_scores
    top_n_scores = top_n_scores.append(p.head(n))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'
```

https://stackoverflow.com/q/75956209

**Comment by Benjamin-Loison** [comment]
https://github.com/swapUniba/UMAP23_KARSCombiningGNNsEncSentenceEnc/pull/3
